<a href="https://colab.research.google.com/github/ngzhiwei517/Machine_Learning_Self-Learn/blob/main/K_fold_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [19]:
lr=LogisticRegression()
lr.fit(X_train,y_train)


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

### Logistic Regression

In [20]:
lr.score(X_test,y_test)

0.9537037037037037

### SVM

In [21]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test, y_test)

0.987037037037037

### Random Forest

In [22]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9666666666666667

We notice some problem the number changes everytime we run the model due to different training set and test set

## KFold cross validation

In [26]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=4) #  This means 4-fold cross-validation.

In [29]:
for train_index,test_index in kf.split([10,9,8,7,6,5,4,3]):
  print(train_index,test_index)

[2 3 4 5 6 7] [0 1]
[0 1 4 5 6 7] [2 3]
[0 1 2 3 6 7] [4 5]
[0 1 2 3 4 5] [6 7]


📌 Important:
These numbers are positions (indices) of [1,2,3,4,5,6,7,8]

Takes 8 samples

Splits them into 4 folds

Each fold has 2 samples as test data

Returns indices, not values ❗

## Use KFold for our digits example

In [30]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [33]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9611111111111111

In [60]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
score_log=[]
score_svm=[]
score_rf=[]

for train_index,test_index in folds.split(digits.data,digits.target):
  X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  score_log.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
  score_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
  score_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [55]:
score_log

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [56]:
score_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [57]:
score_rf

[0.9265442404006677, 0.9649415692821369, 0.9165275459098498]

in real life can just use cross_val score

In [63]:
from sklearn.model_selection import  cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3) #by default is 5

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92153589, 0.94156928, 0.91652755])

In [65]:
from sklearn.model_selection import  cross_val_score
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3) #by default is 5

array([0.38063439, 0.41068447, 0.51252087])

In [62]:
from sklearn.model_selection import  cross_val_score
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3) #by default is 5

array([0.93322204, 0.96327212, 0.93489149])



---



---



---

# Exercise

Create a simple KFold splitter with 5 folds and visualize how it splits a small array [1,2,3,4,5,6,7,8,9,10].

In [43]:
from sklearn.model_selection import KFold
import numpy as np

data = np.array([1,2,3,4,5,6,7,8,9,10])
kf=KFold(n_splits=5)


In [44]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9,10]):
  print(train_index,test_index)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


Load the wine dataset and perform a simple train-test split with one model to establish a baseline.

Use cross_val_score to evaluate the same Random Forest on wine dataset with 5-fold CV. Compare with single split.

In [50]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

wine = load_wine()
X, y = wine.data, wine.target

In [68]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
model=RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [69]:
model.score(X_test,y_test)

1.0

When using cross_val_score, X should be the full dataset (all your data), not just X_train or X_test.

cross_val_score performs its own splitting internally:

By default, it does 5-fold cross-validation on the entire X and y you pass

It automatically creates train/validation folds

It returns scores on the validation folds (not your separate test set

In [71]:
cross_val_score(RandomForestClassifier(n_estimators=100,random_state=42),X,y)

array([0.97222222, 0.94444444, 0.97222222, 0.97142857, 1.        ])

Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

Logistic Regression

SVM

Decision Tree

Random Forest